name: deploy_firebase_hosting
on:
  push:
    branches:
      - master
jobs:
  deploy_firebase_hosting:
    runs-on: macos-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@master
        # node_modules取得
      - name: Install Dependencies
        run: npm install
        # ビルドファイル
      - name: Build
        run: npm run build
        # Firebaseのデプロイコマンド
      - name: Deploy to Firebase
        run: npm run deploy --token=${{ secrets.FIREBASE_DEPLOY_TOKEN }}
