name: deploy_firebase_hosting
on:
  push:
    branches:
      - master
jobs:
  deploy_firebase_hosting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@master
        # node_modules取得
      - name: Install Dependencies
        run: yarn install
        # ビルドファイル
      - name: Build
        run: yarn run build
        # Firebaseのデプロイコマンド
      - name: Deploy to Firebase
        run: yarn deploy --token=${{ secrets.FIREBASE_TOKEN }}
